### ISSUE TITLE
how do i use this plugin with turtlebot3_navigation?

### ISSUE THREAD

**Issue by adi-0906** [jrabel/rrt_planner#1]
Hi! firstly thanks for creating this repository. I am new to ROS and consequently to the navigation stack. I had followed the tutorials via http://emanual.robotis.com/docs/en/platform/turtlebot3/navigation/#ros-1-navigation
I want to use your plugin for the same.
can you please help me out? I have already seen the documentation and some videos but to no avail.

thanks again!

**Comment by jrabel** [comment]
Thanks for looking into my repo and reaching out! Using this repo as a plugin for turtlebot should hopefully be straight forward. 

- First, you should just have to build this package on your system. This should be straight forward, and the process is shown in the README.md. You should be able to query your system to see what planner plugins are available using the following command: `rospack plugins --attrib=plugin nav_core`. You should see the RRTPlanner under the resulting list of planners.
- Second, you should just have to set the `base_global_planner` parameter created and used by the move_base package to "rrt_planner/RRTPlanner". This can be done a number of ways. For example, you can set the parameter through the command line: `rosparam set move_base/base_global_planner rrt_planner/RRTPlanner`. Additionally, you can set this parameter in the launch file you are using to spin up your turtlebot3 simulation. Here, you should add a line under the xml node that launches the move_base node to set the parameter: `<param name="base_global_planner" value="rrt_planner/RRTPlanner" />`. I'd recommend the second option just because it automates the setting of your global planner rather than having you manually set it each time.

Some resources to check out to better understand this process:
- [Writing A Global Path Planner As Plugin in ROS](http://wiki.ros.org/navigation/Tutorials/Writing%20A%20Global%20Path%20Planner%20As%20Plugin%20in%20ROS) - Check out Sections 2.4 and 3 for info on querying available planners and using a plugin.
- [move_base Package Summary](http://wiki.ros.org/move_base) - You can see how this node uses the "base_global_planner" parameter to determine which global planner to use.

Good luck!

**Comment by adi-0906** [comment]
Hi Justin, thanks for reaching out to me and helping. I am already aware of the steps you have mentioned, the issue I'm encountering is the following.
```
/home/aditya/catkin_ws/src/rrt_planner/src/RRTree.h:4:10: fatal error: pcl/octree/octree_search.h: No such file or directory
 #include <pcl/octree/octree_search.h>
```
ros melodic doesn't have the pcl package.


I also get the same error with other plugins that I've installed. can you please tell me where I'm going wrong?
thanks in advance!

**Comment by adi-0906** [comment]
I think I found the source of the first error. 
in 
```
#include<pcl/octree/octree_search.h>
```
there should be a '/' before pcl, (for me at least)
correct me if I'm wrong please.
that's  preventing the file from compiling.

**Comment by jrabel** [comment]
I believe that ROS Melodic should come with pcl and also the pcl_ros package. It looks like cmake is just having trouble finding the pcl include directories. Even though I did not do so for this package, it looks like it is best practice to include/link pcl to your executables in the CMakeLists.txt file when using the library. (I must be using another package/library that brings in pcl already as I'm not getting any compilation/linking errors on my machine.)

I don't know if you have tried this, but the easiest potential fix I can think of is to edit the CMakeLists.txt file to find, include, then link the executables to pcl as described by [this post.](https://answers.ros.org/question/123261/unable-to-include-pcl-files-in-header/)

```
find_package( PCL REQUIRED )
include_directories(  ${catkin_INCLUDE_DIRS}  ${PCL_INCLUDE_DIRS} )
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
target_link_libraries ( rrt_planner ${PCL_LIBRARIES} ${catkin_LIBRARIES} )
```

You could also check out this [PCL Tutorial](http://wiki.ros.org/pcl/Tutorials) as a way to see if you can create a very basic package on your machine with pcl included.

Hope this helps.

**Comment by adi-0906** [comment]
Hi Justin, thank you for your response. Whilst I've learned a lot from it, I was not able to adapt it to my project. Nevertheless, I am glad people like you are out there who make code open-source to make our lives easier.
